#!/usr/bin/env python3
"""Regenerate Rich Black desktop-theme outputs from Theme.qml.

Subcommands:
  render (default)  Regenerate all generated files deterministically.
  check             (a) Fail if on-disk generated files drift from what a
                    fresh render would produce; (b) fail if the
                    hand-authored gtk-3.0/gtk.css / gtk-4.0/gtk.css files
                    contain raw colors (hex literals, raw color functions
                    such as rgb()/rgba()/hsl()/hsla()/hwb()/lab()/lch()/
                    oklab()/oklch()/color-mix()/alpha()/shade()/mix()/
                    lighter()/darker(), or CSS named colors -- they must
                    use only @rb_* / libadwaita @-names); (c) fail if any
                    @NAME referenced in gtk-3.0/gtk.css / gtk-4.0/gtk.css
                    is not defined by the sibling colors.css
                    @define-color set or by a @define-color in the gtk.css
                    file itself; (d) fail if the qt6ct palette ROLES list
                    drifts from the Qt>=6.6 QPalette::ColorRole order
                    (including the NoRole slot) or the golden ToolTipBase /
                    ToolTipText / PlaceholderText / Accent bindings break.
                    Missing gtk.css files are skipped with a note.

All generated files carry a "generated by ... -- do not edit" header.
Rendering is idempotent: stable ordering, no timestamps.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import theme_tokens  # noqa: E402

CONFIG_ROOT = HERE.parent  # ~/.config
TEMPLATE = HERE / "templates" / "rich-black.qss.tmpl"

HEADER_COMMENT = (
    "Generated by desktop-theme/generate.py from "
    "quickshell/theme/Theme.qml -- do not edit."
)

# (Theme.qml name, colors.css name), in stable emission order.
CORE_TOKENS = [
    ("bg", "rb_bg"),
    ("base", "rb_base"),
    ("mantle", "rb_mantle"),
    ("surface0", "rb_surface0"),
    ("surface1", "rb_surface1"),
    ("surface2", "rb_surface2"),
    ("text", "rb_text"),
    ("subtext1", "rb_subtext1"),
    ("subtext0", "rb_subtext0"),
    ("border", "rb_border"),
    ("focusBorder", "rb_focus"),
    ("accent", "rb_accent"),
    ("accentMuted", "rb_accent_muted"),
    ("scrim", "rb_scrim"),
    ("red", "rb_red"),
    ("green", "rb_green"),
    ("mauve", "rb_mauve"),
    ("teal", "rb_teal"),
    ("pink", "rb_pink"),
    ("blue", "rb_blue"),
    ("base3", "rb_base3"),
]

# (libadwaita name, rb_ name it references), in stable emission order.
LIBADWAITA = [
    ("window_bg_color", "rb_bg"),
    ("window_fg_color", "rb_text"),
    ("view_bg_color", "rb_bg"),
    ("view_fg_color", "rb_text"),
    ("headerbar_bg_color", "rb_base"),
    ("headerbar_fg_color", "rb_text"),
    ("popover_bg_color", "rb_mantle"),
    ("popover_fg_color", "rb_text"),
    ("dialog_bg_color", "rb_base"),
    ("dialog_fg_color", "rb_text"),
    ("card_bg_color", "rb_mantle"),
    ("card_fg_color", "rb_text"),
    ("sidebar_bg_color", "rb_base"),
    ("sidebar_fg_color", "rb_text"),
    ("accent_bg_color", "rb_accent"),
    ("accent_fg_color", "rb_bg"),
    ("accent_color", "rb_accent"),
    ("destructive_bg_color", "rb_red"),
    ("destructive_fg_color", "rb_bg"),
    ("success_bg_color", "rb_green"),
    ("success_fg_color", "rb_bg"),
    ("warning_bg_color", "rb_mauve"),
    ("warning_fg_color", "rb_bg"),
    ("error_bg_color", "rb_red"),
    ("error_fg_color", "rb_bg"),
    ("borders", "rb_border"),
    ("shade_color", "rb_scrim"),
    ("scrollbar_outline_color", "rb_border"),
]

# qt6ct palette role order. This MUST match QPalette::ColorRole exactly:
# WindowText(0), Button(1), Light(2), Midlight(3), Dark(4), Mid(5),
# Text(6), BrightText(7), ButtonText(8), Base(9), Window(10), Shadow(11),
# Highlight(12), HighlightedText(13), Link(14), LinkVisited(15),
# AlternateBase(16), NoRole(17), ToolTipBase(18), ToolTipText(19),
# PlaceholderText(20), Accent(21), NColorRoles(22) for Qt >= 6.6.
# See /usr/include/qt6/QtGui/qpalette.h ("Do not change the order, the
# serialization format depends on it"). qt6ct maps list index i ->
# ColorRole(i), so omitting NoRole shifts everything from ToolTipBase on
# by one (near-white placeholders, mis-bound Accent). NoRole is unused
# by Qt; its slot carries the mantle filler so indices stay aligned.
ROLES = [
    "WindowText",
    "Button",
    "Light",
    "Midlight",
    "Dark",
    "Mid",
    "Text",
    "BrightText",
    "ButtonText",
    "Base",
    "Window",
    "Shadow",
    "Highlight",
    "HighlightedText",
    "Link",
    "LinkVisited",
    "AlternateBase",
    "NoRole",
    "ToolTipBase",
    "ToolTipText",
    "PlaceholderText",
    "Accent",
]

# Canonical Qt >= 6.6 QPalette::ColorRole order, hardcoded as a literal so
# the order/count guard in cmd_check can actually fail. Do NOT derive this
# from ROLES (``EXPECTED_ROLES = list(ROLES)`` would be unfalsifiable).
# Verified against /usr/include/qt6/QtGui/qpalette.h:
#   enum ColorRole { WindowText, Button, Light, Midlight, Dark, Mid,
#                    Text, BrightText, ButtonText, Base, Window, Shadow,
#                    Highlight, HighlightedText, Link, LinkVisited,
#                    AlternateBase, NoRole, ToolTipBase, ToolTipText,
#                    PlaceholderText, Accent, NColorRoles = Accent + 1 };
# NColorRoles = Accent+1 = 22.
EXPECTED_ROLES = [
    "WindowText",
    "Button",
    "Light",
    "Midlight",
    "Dark",
    "Mid",
    "Text",
    "BrightText",
    "ButtonText",
    "Base",
    "Window",
    "Shadow",
    "Highlight",
    "HighlightedText",
    "Link",
    "LinkVisited",
    "AlternateBase",
    "NoRole",
    "ToolTipBase",
    "ToolTipText",
    "PlaceholderText",
    "Accent",
]
QT66_NCOLORROLES = 22

# Golden active bindings for the roles around the NoRole slot.
PALETTE_GOLDEN = {
    "NoRole": "mantle",
    "ToolTipBase": "mantle",
    "ToolTipText": "text",
    "PlaceholderText": "subtext0",
    "Accent": "accent",
}

# ACTIVE role -> Theme.qml token (or a literal hex where no token applies).
ACTIVE_MAP = {
    "WindowText": "text",
    "Button": "mantle",
    "Light": "surface1",
    "Midlight": "surface0",
    "Dark": "bg",
    "Mid": "surface1",
    "Text": "text",
    "BrightText": "base3",
    "ButtonText": "text",
    "Base": "bg",
    "Window": "base",
    "Shadow": "#000000",
    "Highlight": "accent",
    "HighlightedText": "bg",
    "Link": "blue",
    "LinkVisited": "mauve",
    "AlternateBase": "surface0",
    "NoRole": "mantle",
    "ToolTipBase": "mantle",
    "ToolTipText": "text",
    "PlaceholderText": "subtext0",
    "Accent": "accent",
}

# Deltas applied on top of ACTIVE_MAP.
DISABLED_OVERRIDES = {
    "WindowText": "subtext0",
    "Text": "subtext0",
    "BrightText": "subtext0",
    "ButtonText": "subtext0",
    "ToolTipText": "subtext0",
    "PlaceholderText": "subtext0",
    "Highlight": "surface2",
    "HighlightedText": "subtext0",
    "Link": "subtext0",
    "LinkVisited": "subtext0",
    "Accent": "surface2",
}

INACTIVE_OVERRIDES = {
    "WindowText": "subtext1",
    "Text": "subtext1",
    "BrightText": "subtext1",
    "ButtonText": "subtext1",
    "ToolTipText": "subtext1",
    # PlaceholderText stays subtext0 (same as active): it is already
    # dimmer than subtext1, and brightening a placeholder when a window
    # goes inactive would be wrong.
    "Highlight": "surface2",
    "HighlightedText": "subtext1",
    "Link": "subtext1",
    "LinkVisited": "subtext1",
    "Accent": "accentMuted",
}

DISABLED_MAP = {**ACTIVE_MAP, **DISABLED_OVERRIDES}
INACTIVE_MAP = {**ACTIVE_MAP, **INACTIVE_OVERRIDES}

PLACEHOLDER_RE = re.compile(r"\{\{(\w+)\}\}")
RAW_HEX_RE = re.compile(r"#[0-9a-fA-F]{3,8}\b")
RGBA_RE = re.compile(r"rgba\s*\(")
# Any raw color function: a literal computed in the stylesheet instead of
# a token reference. Case-insensitive; checked against comment-stripped
# source so prose (e.g. "Rich Black") can't trip the named-color rule.
RAW_FUNC_RE = re.compile(
    r"(?i)\b(?:rgb|rgba|hsl|hsla|hwb|lab|lch|oklab|oklch|color-mix|"
    r"alpha|shade|mix|lighter|darker)\s*\("
)
CSS_NAMED_COLOR_RE = re.compile(
    r"(?i)\b(?:aliceblue|antiquewhite|aqua|aquamarine|azure|beige|"
    r"bisque|black|blanchedalmond|blue|blueviolet|brown|burlywood|"
    r"cadetblue|chartreuse|chocolate|coral|cornflowerblue|cornsilk|"
    r"crimson|cyan|darkblue|darkcyan|darkgoldenrod|darkgray|darkgreen|"
    r"darkgrey|darkkhaki|darkmagenta|darkolivegreen|darkorange|"
    r"darkorchid|darkred|darksalmon|darkseagreen|darkslateblue|"
    r"darkslategray|darkslategrey|darkturquoise|darkviolet|deeppink|"
    r"deepskyblue|dimgray|dimgrey|dodgerblue|firebrick|floralwhite|"
    r"forestgreen|fuchsia|gainsboro|ghostwhite|gold|goldenrod|gray|"
    r"green|greenyellow|grey|honeydew|hotpink|indianred|indigo|ivory|"
    r"khaki|lavender|lavenderblush|lawngreen|lemonchiffon|lightblue|"
    r"lightcoral|lightcyan|lightgoldenrodyellow|lightgray|lightgreen|"
    r"lightgrey|lightpink|lightsalmon|lightseagreen|lightskyblue|"
    r"lightslategray|lightslategrey|lightsteelblue|lightyellow|lime|"
    r"limegreen|linen|magenta|maroon|mediumaquamarine|mediumblue|"
    r"mediumorchid|mediumpurple|mediumseagreen|mediumslateblue|"
    r"mediumspringgreen|mediumturquoise|mediumvioletred|midnightblue|"
    r"mintcream|mistyrose|moccasin|navajowhite|navy|oldlace|olive|"
    r"olivedrab|orange|orangered|orchid|palegoldenrod|palegreen|"
    r"paleturquoise|palevioletred|papayawhip|peachpuff|peru|pink|"
    r"plum|powderblue|purple|rebeccapurple|red|rosybrown|royalblue|"
    r"saddlebrown|salmon|sandybrown|seagreen|seashell|sienna|silver|"
    r"skyblue|slateblue|slategray|slategrey|snow|springgreen|steelblue|"
    r"tan|teal|thistle|tomato|turquoise|violet|wheat|white|whitesmoke|"
    r"yellow|yellowgreen)\b"
)
CSS_COMMENT_RE = re.compile(r"/\*.*?\*/", re.DOTALL)
DEFINE_COLOR_RE = re.compile(r"@define-color\s+([A-Za-z_][A-Za-z0-9_-]*)")
AT_REF_RE = re.compile(r"@(-?[A-Za-z_][A-Za-z0-9_-]*)")
# Non-color at-rules/keywords that may appear as @NAME but are never
# color references.
AT_RULE_EXCLUDE = frozenset(
    {
        "import",
        "define-color",
        "media",
        "keyframes",
        "charset",
        "font-face",
        "page",
        "supports",
        "document",
        "namespace",
    }
)


def build_colors_css() -> str:
    """Render a gtk colors.css: rb_ tokens + libadwaita contract."""
    lines = [f"/* {HEADER_COMMENT} */"]
    for theme_name, rb_name in CORE_TOKENS:
        lines.append(f"@define-color {rb_name} {theme_tokens.css(theme_name)};")
    lines.append("")
    lines.append("/* libadwaita named-color contract (references the rb_ tokens). */")
    for lib_name, rb_name in LIBADWAITA:
        lines.append(f"@define-color {lib_name} @{rb_name};")
    return "\n".join(lines) + "\n"


def _aarrggbb(value: str) -> str:
    """Normalize a token/literal hex to lowercase #aarrggbb (opaque: ff...)."""
    text = value.strip()
    if not text.startswith("#"):
        raise ValueError(f"Not a hex color: {value!r}")
    digits = text[1:]
    if len(digits) == 6:
        return "#ff" + digits.lower()
    if len(digits) == 8:
        return "#" + digits.lower()
    raise ValueError(f"Unsupported hex color: {value!r}")


def _palette_value(spec: str) -> str:
    if spec.startswith("#"):
        return _aarrggbb(spec)
    value = theme_tokens.tokens()[spec]
    if isinstance(value, int):
        raise TypeError(f"Token {spec!r} is an int, not a color")
    return _aarrggbb(value)


def build_rich_black_conf() -> str:
    """Render qt6ct/colors/rich-black.conf ([ColorScheme] palette)."""
    lines = [
        f"# {HEADER_COMMENT}",
        "[ColorScheme]",
        "# Role order: " + ", ".join(ROLES) + ".",
    ]
    for label, table in (
        ("active", ACTIVE_MAP),
        ("disabled", DISABLED_MAP),
        ("inactive", INACTIVE_MAP),
    ):
        values = ", ".join(_palette_value(table[role]) for role in ROLES)
        lines.append(f"{label}_colors={values}")
    return "\n".join(lines) + "\n"


def build_qss() -> str:
    """Render qt6ct/qss/rich-black.qss from the template.

    Every ``{{name}}`` placeholder is substituted: color tokens via
    ``theme_tokens.qss(name)``, radius/int tokens via their integer
    value. Unknown placeholders are a hard error.
    """
    template = TEMPLATE.read_text(encoding="utf-8")
    data = theme_tokens.tokens()

    def replace(match: re.Match) -> str:
        name = match.group(1)
        if name not in data:
            raise ValueError(
                f"Unknown placeholder '{{{{{name}}}}}' in {TEMPLATE}; "
                "it matches no Theme.qml color or int token."
            )
        value = data[name]
        if isinstance(value, int):
            return str(value)
        return theme_tokens.qss(name)

    rendered = PLACEHOLDER_RE.sub(replace, template)
    if not rendered.endswith("\n"):
        rendered += "\n"
    return f"/* {HEADER_COMMENT} */\n" + rendered


def build_all() -> dict[Path, str]:
    """Render every generated file; return {absolute path: content}."""
    colors_css = build_colors_css()
    return {
        CONFIG_ROOT / "gtk-3.0" / "colors.css": colors_css,
        CONFIG_ROOT / "gtk-4.0" / "colors.css": colors_css,
        CONFIG_ROOT / "qt6ct" / "colors" / "rich-black.conf": (
            build_rich_black_conf()
        ),
        CONFIG_ROOT / "qt6ct" / "qss" / "rich-black.qss": build_qss(),
    }


def cmd_render() -> int:
    planned = build_all()
    for path, content in planned.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path}")
    return 0


def cmd_check() -> int:
    errors: list[str] = []

    planned = build_all()
    for path, content in planned.items():
        if not path.exists():
            errors.append(f"missing generated file: {path} (run 'render')")
        elif path.read_text(encoding="utf-8") != content:
            errors.append(f"drift detected: {path} differs; run 'render'")

    # Rule (d): palette role order/count guard. The qt6ct [ColorScheme]
    # contract maps list index i -> QPalette::ColorRole(i), so ROLES must
    # match the Qt >= 6.6 enum exactly (including the NoRole slot) and
    # the golden roles around it must keep their token bindings.
    if ROLES != EXPECTED_ROLES:
        errors.append(
            "palette ROLES drifted from the Qt>=6.6 QPalette::ColorRole "
            f"order: {ROLES!r} != {EXPECTED_ROLES!r}"
        )
    if len(ROLES) != QT66_NCOLORROLES:
        errors.append(
            f"palette role count {len(ROLES)} != QPalette::NColorRoles "
            f"({QT66_NCOLORROLES}) for Qt>=6.6; the NoRole slot may be missing"
        )
    for role, token in PALETTE_GOLDEN.items():
        if ACTIVE_MAP.get(role) != token:
            errors.append(
                f"palette ACTIVE_MAP[{role!r}] is {ACTIVE_MAP.get(role)!r}, "
                f"expected token {token!r}"
            )
    conf_text = planned[CONFIG_ROOT / "qt6ct" / "colors" / "rich-black.conf"]
    active_line = next(
        (
            line
            for line in conf_text.splitlines()
            if line.startswith("active_colors=")
        ),
        "",
    )
    active_values = active_line.partition("=")[2].split(", ")
    for role in ("NoRole", "ToolTipBase", "ToolTipText", "PlaceholderText",
                 "Accent"):
        try:
            index = ROLES.index(role)
        except ValueError:
            errors.append(f"palette ROLES missing role {role!r}")
            continue
        expected = _palette_value(ACTIVE_MAP[role])
        got = active_values[index] if index < len(active_values) else "<short>"
        if got != expected:
            errors.append(
                f"palette active_colors[{index}] ({role}) is {got}, "
                f"expected {expected}; role order is shifted"
            )

    for css_path in (
        CONFIG_ROOT / "gtk-3.0" / "gtk.css",
        CONFIG_ROOT / "gtk-4.0" / "gtk.css",
    ):
        if not css_path.exists():
            print(f"note: {css_path} absent, skipping raw-color rule")
            continue
        text = css_path.read_text(encoding="utf-8")
        probe_text = CSS_COMMENT_RE.sub("", text)
        hex_hit = RAW_HEX_RE.search(probe_text)
        rgba_hit = RGBA_RE.search(probe_text)
        func_hit = RAW_FUNC_RE.search(probe_text)
        named_hit = CSS_NAMED_COLOR_RE.search(probe_text)
        if hex_hit:
            errors.append(
                f"{css_path} contains raw hex color {hex_hit.group(0)!r}; "
                "use @rb_* / libadwaita @-names only"
            )
        if rgba_hit:
            errors.append(
                f"{css_path} contains an rgba() literal; "
                "use @rb_* / libadwaita @-names only"
            )
        if func_hit:
            errors.append(
                f"{css_path} contains a raw color function "
                f"{func_hit.group(0)!r}; use @rb_* / libadwaita @-names only"
            )
        if named_hit:
            errors.append(
                f"{css_path} contains a CSS named color "
                f"{named_hit.group(0)!r}; use @rb_* / libadwaita @-names only"
            )

    # Rule (c): every @NAME referenced in gtk.css must be defined by the
    # sibling colors.css @define-color set or by a @define-color in the
    # gtk.css file itself (locally-defined names are valid).
    for css_path in (
        CONFIG_ROOT / "gtk-3.0" / "gtk.css",
        CONFIG_ROOT / "gtk-4.0" / "gtk.css",
    ):
        if not css_path.exists():
            print(f"note: {css_path} absent, skipping token-reference rule")
            continue
        colors_path = css_path.parent / "colors.css"
        if not colors_path.exists():
            errors.append(
                f"{css_path} has no sibling {colors_path}; "
                "cannot resolve @-name references"
            )
            continue
        css_text = css_path.read_text(encoding="utf-8")
        defined = set(
            DEFINE_COLOR_RE.findall(
                colors_path.read_text(encoding="utf-8")
            )
        ) | set(DEFINE_COLOR_RE.findall(css_text))
        referenced: set[str] = set()
        for line in css_path.read_text(encoding="utf-8").splitlines():
            # The name being defined on its own @define-color line is a
            # definition, not a reference.
            probe = DEFINE_COLOR_RE.sub("", line)
            for match in AT_REF_RE.finditer(probe):
                name = match.group(1)
                if name in AT_RULE_EXCLUDE:
                    continue
                if name.startswith("-"):
                    # @-gtk-...-style vendor at-rules.
                    continue
                referenced.add(name)
        undefined = sorted(referenced - defined)
        if undefined:
            errors.append(
                f"{css_path} references undefined color(s): "
                + ", ".join(f"@{name}" for name in undefined)
                + f" (not defined in {colors_path})"
            )

    if errors:
        for message in errors:
            print(f"FAIL: {message}", file=sys.stderr)
        return 1
    print(
        f"OK: {len(planned)} generated files match Theme.qml; "
        "gtk.css raw-color rule holds; gtk.css token references resolve."
    )
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Regenerate Rich Black theme files from Theme.qml."
    )
    parser.add_argument(
        "command",
        nargs="?",
        choices=("render", "check"),
        default="render",
        help="render generated files (default) or check them for drift",
    )
    args = parser.parse_args(argv)
    try:
        if args.command == "check":
            return cmd_check()
        return cmd_render()
    except (ValueError, KeyError, TypeError) as exc:
        print(f"FAIL: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
