# The empty monitor entry is the fallback for outputs not listed below.
wallpaper {
  monitor =
  path = ~/Bilder/wall.jpg
  fit_mode = cover
}
wallpaper  { 
  monitor = eDP-1
  path = ~/Bilder/wall.jpg
  fit_mode = cover
}
wallpaper  { 
  monitor = DP-1
  path = ~/Bilder/wall.jpg
  fit_mode = cover
}
wallpaper  { 
  monitor = DP-2
  path = ~/Bilder/wall.jpg
  fit_mode = cover
}
wallpaper  { 
  monitor = DP-3
  path = ~/Bilder/wall.jpg
  fit_mode = cover
}
#if more than one monitor in use, can load a 2nd image

#enable splash text rendering over the wallpaper
splash = false

#fully disable ipc
# ipc = off
