preload = ~/Pictures/wall.jpg
#if more than one preload is desired then continue to preload other backgrounds
# .. more preloads

#set the default wallpaper(s) seen on initial workspace(s) --depending on the number of monitors used
wallpaper  { 
  monitor = DP-1
  path = ~/Pictures/wall.jpg
  fit_mode = cover
}
wallpaper  { 
  monitor = DP-2
  path = ~/Pictures/wall.jpg
  fit_mode = cover
}
wallpaper  { 
  monitor = DP-3
  path = ~/Pictures/wall.jpg
  fit_mode = cover
}
#if more than one monitor in use, can load a 2nd image

#enable splash text rendering over the wallpaper
splash = true

#fully disable ipc
# ipc = off


