hl.on("hyprland.start", function()
	hl.exec_cmd(TERMINAL)
	hl.exec_cmd("quickshell & hyprpaper")
	hl.exec_cmd("evolution")
	hl.exec_cmd("wl-paste --watch cliphist store")
	hl.dsp.workspace.toggle_special("journal")
end)
